### ISSUE TITLE
Typo in description of DUPLICATE_PRIMARY_TIMEOUT parameter in man pages?

### ISSUE THREAD

**Issue by fdanapfel** [SUSE/SAPHanaSR-ScaleOut#126]
The description for the DUPLICATE_PRIMARY_TIMEOUT parameter at https://github.com/SUSE/SAPHanaSR-ScaleOut/blob/925a7809ac987db35a348d18b1644d4ccb994387/SAPHana/man/ocf_suse_SAPHanaController.7#L135 mentions DUPLICATE_PRIMARY_TIMESTAMP twice.

I guess DUPLICATE_PRIMARY_TIMESTAMP should actually be DUPLICATE_PRIMARY_TIMEOUT?

**Comment by lpinne** [comment]
Hi Frank,
thanks a lot!
Will be fixed with pr #127 .
So I close this issue.
Regards,
Lars
