### ISSUE TITLE
Error in Ressource Agent function is_clone "compare string with integer"

### ISSUE THREAD

**Issue by mmoster** [SUSE/SAPHanaSR-ScaleOut#24]
During the simulation of the resource agents, I got error messages.
It looks like that there are string with integer comparism,

I did this simulation:
CLACT=_clone OCF_RESKEY_CRM_meta_clone_max=2 OCF_RESKEY_DIR_EXECUTABLE=/usr/sap/RH1/HDB00/exe/ OCF_RESKEY_SID=RH1  OCF_RESKEY_InstanceNumber=00 OCF_ROOT=/usr/lib/ocf /usr/lib/ocf/resource.d/heartbeat/SAPHanaTopology status                                                                                            
INFO: DEC: site=DC1, mode=primary, MAPPING=
/usr/lib/ocf/resource.d/heartbeat/SAPHanaTopology: line 316: [: : integer expression expected

Here is the code listing:
305 function is_clone() {
 306     super_ocf_log info "FLOW $FUNCNAME ($*)"
 307     local rc=0
 308     #
 309     # is a clone config?
 310     #
 311     if [ -n "$OCF_RESKEY_CRM_meta_clone_max" ] \
 312        && [ "$OCF_RESKEY_CRM_meta_clone_max" -gt 0 ]; then
 313        #
 314        # yes it is a clone config - check, if its configured well
 315        #
 316         if [ "$OCF_RESKEY_CRM_meta_clone_node_max" -ne 1 ] ; then

Line 311 and Line 316 need to be checked. Integer is compared with string

Then I did the same test with SAPHanaController

CLACT=_clone OCF_RESKEY_CRM_meta_clone_max=1 OCF_RESKEY_DIR_EXECUTABLE=/usr/sap/RH1/HDB00/exe/ OCF_RESKEY_SID=RH1  OCF_RESKEY_InstanceNumber=00 OCF_ROOT=/usr/lib/ocf /usr/lib/ocf/resource.d/heartbeat/SAPHanaController status

INFO: DEC: is_master_nameserver  rc=0
INFO: DEC: ===> master_walk: priorities for site DC1 master1=lsh40401 master2=lsh40403 master3= ==> active_master=lsh40401 best_cold_master=
INFO: DEC: ===> master_walk: the_master=lsh40401;
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
/usr/lib/ocf/resource.d/heartbeat/SAPHanaController: line 402: [: : integer expression expected
/usr/lib/ocf/resource.d/heartbeat/SAPHanaController: line 403: [: : integer expression expected
/usr/lib/ocf/resource.d/heartbeat/SAPHanaController: line 404: [: : integer expression expected
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INFO: RA ==== begin action monitor_clone (0.164.2) ====
INFO: RA: SRHOOK01=SOK
INFO: RA: SRHOOK03=SOK
INFO: RA: SRHOOK01=SOK
INFO: RA: SRHOOK03=SOK
4:P:master1:master:worker:master
SOK
...

It is again the function is_clone now in SAPHanaController

Here is the listing:
391 function is_clone() {
 392     super_ocf_log info "FLOW $FUNCNAME ($*)"
 393     local rc=0
 394     #
 395     # is a clone config?
 396     #
 397     if [ -n "$OCF_RESKEY_CRM_meta_clone_max" ] \
 398        && [ "$OCF_RESKEY_CRM_meta_clone_max" -gt 0 ]; then
 399        #
 400        # yes it is a clone config - check, if its configured well
 401        #
 402         if [ "$OCF_RESKEY_CRM_meta_clone_node_max" -ne 1 ] || \
 403             [ "$OCF_RESKEY_CRM_meta_master_node_max" -ne 1 ] || \
 404             [ "$OCF_RESKEY_CRM_meta_master_max" -ne 1 ]; then
 405                 super_ocf_log err "ACT: Clone options misconfigured. (expect: clone_node_max=1,master_node_max=1,master_max=1)"
 406                 exit $OCF_NOT_RUNNING

Line 398 402 403 and 404 needs to be checked.

i will test also some potential fixes.

**Comment by fmherschel** [comment]
Hmm the basic coding works:

suse11:/usr/lib/python3.6/site-packages/crmsh # if [ "1" -gt 0 ]; then echo ja; else echo no; fi
ja
suse11:/usr/lib/python3.6/site-packages/crmsh # if [ "0" -gt 0 ]; then echo ja; else echo no; fi
no

in your case you did not set OCF_RESKEY_CRM_meta_clone_node_max. The cluster would always set these values to an non empty variable.

So your testing is broken in my opinion

**Comment by fmherschel** [comment]
BTW you could not test SAPHana* "offline" so without the cluster, because the RA needs the cluster to set/get the SAPHana* cluster attributes. So this is not the same as IPAddr2.

**Comment by fmherschel** [comment]
You get the "integer expression expected", because you did not even set any value in your case. Comaring VAR=1; if [ "$VAR" -eq 1 ]; then ... fi works perfect.
You get the error when VAR es empty which "compiles" to if <empty-STRING> -eq 1

**Comment by fmherschel** [comment]
If you set OCF_RESKEY_CRM_meta_clone_max you need to play a fair cluster and also set ALL other OCF_RESKEY_CRM_meta_{clone|master}_* variables like:
OCF_RESKEY_CRM_meta_clone_node_max
OCF_RESKEY_CRM_meta_master_node_max
OCF_RESKEY_CRM_meta_master_max

While the "failed" code in your case only rises, if you set OCF_RESKEY_CRM_meta_clone_max and the cluster would (in clone cases) always set OCF_RESKEY_CRM_meta_clone* and (for ms cases) OCF_RESKEY_CRM_meta_master_* the code is save and well capable.

**Comment by mmoster** [comment]
Thanks for the feedback.
Yes test will only run on a pacemaker and HANA environment, which I did.
Yes the manual tests with comparison works fine.
Yes if I am using OCF_RESKEY_CRM_meta_clone_max this part of code will not be used and so there is no error. 
I am pretty sure, this part of code will create this error message,if it is executed. I will try to focus on the necessary code parts.

**Comment by fmherschel** [comment]
@mmoster: Try also to set the OCF_RESKEY_CRM_meta_clone_node_max for SAPHanaTopology the code will be executed and there os no error.

**Comment by mmoster** [comment]
@fmherschel 
Yes you are right.
For example setting: 
OCF_RESKEY_CRM_meta_clone_max=1
OCF_RESKEY_CRM_meta_clone_node_max=2
OCF_RESKEY_CRM_meta_master_node_max=2
OCF_RESKEY_CRM_meta_master_max=2

works fine.
